# run: conda env create -n [ønsket navn] --file environment.yml
#name: test-env
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
- python=3.8
- pip
- numpy
- pandas
- requests
- openpyxl
- matplotlib
- ipykernel
- pip:
  - docx
  - pyjstat
  - PyGithub
  - python-dotenv
  #- gooey # Graphical user interface navigation