# conda env create -f environment.yaml
name: analyse
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - requests
  - openpyxl
  - matplotlib
  - ipykernel
  - beautifulsoup4
  - pypdf2
  - python-dotenv
  - pygithub
  - xlrd
  - aiohttp
  - pip:
      - pyjstat
      - pyautogui
      - keyboard
      - selenium
      - dtale
variables:
  PYTHONPATH: "C:\\Users\\eve1509\\OneDrive - Telemark fylkeskommune\\Github\\Telemark\\Python"
  TEMP_FOLDER: "C:\\Users\\eve1509\\OneDrive - Telemark fylkeskommune\\Github\\Telemark\\Python\\Temp"
  LOG_FOLDER: "C:\\Users\\eve1509\\OneDrive - Telemark fylkeskommune\\Github\\Telemark\\Python\\Log"
