# Opprette environment: conda env create --file environment.yaml
# Oppdatere environment: conda update --file environment.yaml (og så deaktivere og aktivere environment)
name: analyse
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - requests
  - openpyxl
  - matplotlib
  - ipykernel
  - beautifulsoup4
  - pypdf2
  - python-dotenv
  - pygithub
  - xlrd
  - aiohttp
  - pip:
      - pyjstat
      - pyautogui
      - keyboard
      - selenium
      - dtale
variables:
  PYTHONPATH: "C:\\Users\\_eve1509\\Documents\\Github\\Telemark\\Python"
  TEMP_FOLDER: "C:\\Users\\_eve1509\\Documents\\Github\\Telemark\\Python\\Temp"
  LOG_FOLDER: "C:\\Users\\_eve1509\\Documents\\Github\\Telemark\\Python\\Log"
