name: Deploy Webpage to GitHub Pages

on:
  push:
    branches: [main]  # 🚀 Triggers when pushing to main
  workflow_dispatch:  # Allow manual runs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure deployment directory exists
        run: |
          mkdir -p Kart/sirkulare_telemark
          echo "const MAPBOX_ACCESS_TOKEN = '${{ secrets.MAPBOX_ACCESS_TOKEN }}';" > Kart/sirkulare_telemark/config.js
          ls -l Kart/sirkulare_telemark  # Debugging

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Kart/sirkulare_telemark  # ✅ Deploy only this folder
          publish_branch: gh-pages  # ✅ Push only to gh-pages
          keep_files: true  # Prevents deletion of previous files
          force_orphan: false  # Keep commit history
