name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject Mapbox Token
        run: |
          echo "const MAPBOX_ACCESS_TOKEN = '${{ secrets.MAPBOX_ACCESS_TOKEN }}';" > config.js
          cat config.js  # Debugging: Print the file to confirm it exists

      - name: Force Add config.js to Deployment
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory /home/runner/work/Telemark/Telemark

          if [ -f "config.js" ]; then  # Ensure file exists before adding
            git add -f config.js  # Force add config.js
            git commit -m "Add config.js for deployment"
          else
            echo "⚠️ config.js is missing!" && exit 1
          fi

          git status  # Debugging: Check if config.js is staged

      - name: Debug Deployment Files  # 🛠️ Debugging Step
        run: |
          ls -lah  # List all files to check if config.js exists
          git status  # Check what Git sees as changes
          cat config.js  # Print config.js to confirm it exists

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Ensure this matches your GitHub Pages branch
          folder: .  # Deploy everything, including config.js
          clean: true  # Remove old files before deploying
          force: true  # Ensure deployment happens even if no detected changes
          single-commit: false  # Prevent unnecessary re-commits
          commit-message: "Automated deployment including config.js"
